#!/bin/sh
#
# This script is meant to be added to the PATH so the latest azure-cli is
# always ready to use

CONTAINER_NAME=azuresdk/azure-cli-python:0.1.5

pull_container() {
    docker pull ${CONTAINER_NAME}
}

# Pull down the container if we don't already have it
docker inspect ${CONTAINER_NAME} 2>&1 > /dev/null
if [ $? -ne 0 ]; then
    pull_container
fi;

exec docker run --rm  -u $(id -u):$(id -u) \
    -ti \
    -v ${HOME}/.azure:/.azure \
    -v $PWD:/data \
    --workdir=/data \
    ${CONTAINER_NAME} /usr/local/bin/az $@
