#!/bin/sh

tty --quiet

if [ $? -eq 0 ]; then
    TTY_ARGS="-ti"
fi;

exec docker run --rm ${TTY_ARGS} \
        -v $PWD:$PWD \
        -w $PWD \
        $(printenv | grep -i \^packer | awk '{ print "-e", $1 }') \
        hashicorp/packer:light $@
