#!/bin/sh

AZ=$(dirname $0)/az

GROUPS=$(${AZ} group list -o tsv | awk '{ print $4 }' | grep -P "^pr(\d+)")

echo "> Planning to delete:"

for g in $GROUPS; do
    echo ">> ${g}"
done;

read -p "Procees? (yes): " CONFIRM

if [ ! "${CONFIRM}" = "yes" ]; then
    exit 1
fi;

echo "> Deleting.."
set -xe

for g in $GROUPS; do
    echo "> ${g}"
    ${AZ} group delete -n $g
done;
