#!/bin/sh


# local container which will just run Python with PyYaml installed since it's
# not in the default python distribution
CONTAINER=python-yaml
READLINK="readlink -m"
if [[ `uname -s` == 'Darwin' ]]; then
  echo "Using coreutils greadlink"
  READLINK="greadlink -m"
fi

docker inspect -f . ${CONTAINER} > /dev/null
if [ $? -eq 1 ]; then

    cat << EOF | docker build -t ${CONTAINER} --rm -
FROM python:3-alpine
RUN pip install pyyaml
EOF

fi;
exec docker run --rm -i \
    -v $($READLINK $(dirname $0))/../:/data -w /data \
        ${CONTAINER} $@
