#!/bin/sh

# local container which will just run Python with PyYaml installed since it's
# not in the default python distribution
CONTAINER=python-yaml

docker inspect -f . ${CONTAINER} > /dev/null
if [ $? -eq 1 ]; then

    cat << EOF | docker build -t ${CONTAINER} --rm -
FROM python:2-alpine
RUN pip install pyyaml
EOF

fi;
exec docker run --rm -i \
    -v $(readlink -m $(dirname $0))/../:/data -w /data \
        ${CONTAINER} $@
